### ISSUE TITLE
没什么问题,给你点个赞

### ISSUE THREAD

**Issue by liupeng110** [bbssyyuui/ActivityLauncher#3]
使用androidx也是一样的,这个思路很巧妙.
我要封装谷歌/fb登录支付模块作为一个sdk,但是这两种都是通过onActivityResult回调传数据
让我非常纠结还要在sdk里面增加个activity才能实现,(sdk不想增加界面,sdk只负责逻辑)
这个库帮了我大忙!!!

**Comment by bbssyyuui** [comment]
感谢感谢~
